apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portfolio-fs-tls
spec:
  secretName: portfolio-fs-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - g2studio.it.com
