apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-fs
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  rules:
    - host: portfolio-fs.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portfolio-fs
                port:
                  number: 80
  tls:
    - secretName: portfolio-fs-tls
      hosts:
        - portfolio-fs.example.com
