apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-fs
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
  - host: g2studio.it.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portfolio-fs
            port:
              number: 80
  tls:
  - hosts:
    - g2studio.it.com
    secretName: portfolio-fs-tls